#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged to check and fix files before commit
npx lint-staged

# Run type check
npm run type-check

# Run tests related to staged files
npm run test -- --passWithNoTests --findRelatedTests --bail
